title: Singapore Accreditation Council
title-abbreviated: SAC
description: >- # this means to ignore newlines until "baseurl:"
  Description
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: isomerpages/isomerpages-template
safe: false

plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap

# Breadcrumbs
breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

collections:
  about:
    output: true
  industries:
    output: true
  services:
    output: true
  resources:
    output: true

# Resource Room and Pagination
resources_name: "newsroom"
paginate: 12
paginate_path: "/newsroom/page:num"

# Homepage sections
homepage_hero_i_want_to: false # if i_want_to is true, there will be no key highlights
homepage_programmes: true
homepage_resources: true
homepage_careers: true

# Feedback Form URL
feedback_form_url: "https://form.sg/#!/forms/govtech/5a9ce876b3a3b6006e6b8335"

# FAQ URL
faq_url: "/faq/"
faq_url_external: false

# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"



